# Generated by Django 3.2.8 on 2024-07-25 14:15

from django.db import migrations, models
import newapp.models.record


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('pre', models.FileField(upload_to=newapp.models.record.createPath)),
                ('res_path', models.CharField(max_length=150)),
            ],
        ),
    ]
