# Generated by Django 3.2.8 on 2024-07-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='res_path',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
