# Generated by Django 3.2.8 on 2024-07-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20240726_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='ans1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='duser',
            name='ans2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='duser',
            name='que1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='duser',
            name='que2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
